name: Deploy to VPS

on:
  push:
    branches:
      - main  # или другая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: Run Docker Compose on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app
            # Удаление существующего контейнера, если он есть
            docker rm -f nest-app || true
            # Остановка и удаление текущих контейнеров, определенных в docker-compose.yml
            docker-compose down
            # Запуск новых контейнеров
            docker-compose up -d --build
